resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: balajils1/Sampleproject
      gitProvider: balaji
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Art1
      buildName: npm_example
      buildNumber: 1
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name:drydock/u16node
                tag: master
        configuration:
          repositoryName: npm-local
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          integrations:
            - name: Art1
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: build_npm
          integrations:
            - name: Art1
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          #integrations:
          #  - name: Art1
          outputResources:
            - name: helloworld_build_info
