resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      gitProvider: balaji
      path: balajils1/Sampleproject
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Art1
      buildName: npm_example
      buildNumber: 1
      
  - name:       release_bundle
    type:       ReleaseBundle
    configuration:
      sourceArtifactory:    Art1
      name:                 release2
      version:              1.0.0
      isSigned:             false
      
  - name:       release_bundle_new
    type:       ReleaseBundle
    configuration:
      sourceArtifactory:    Art1
      name:                 release2
      version:              1.0.0
      isSigned:             true
      
  - name:           Rule1
    type:           DistributionRule
    configuration:
      sourceArtifactory:    Art1
      serviceName:          A*
      siteName:             A*
      cityName:             A*
      countryCodes:
        - A*
     
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          integrations:
            - name: Art1
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: build_npm
          integrations:
            - name: Art1
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          #integrations:
           # - name: Art1
          outputResources:
            - name: helloworld_build_info
      - name: scan
        type: XrayScan
        configuration:
           #inherits from bash
          inputResources:
            - name: helloworld_build_info
              trigger: true
          waitUntilFinish: true
          
       - name:    distribute
    steps:
      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name:            release_bundle 
              trigger: true
          outputResources:
            - name:            release_bundle_new
      - name: my_distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: release_bundle_new
              trigger: false
            - name: Rule1
              trigger: true
 
        execution:
          onStart:
            - echo "Preparing for work...."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
